"""empty message

Revision ID: 427bbe050a48
Revises: 6d109e137850
Create Date: 2021-02-25 21:42:14.599525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427bbe050a48'
down_revision = '6d109e137850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
