"""empty message

Revision ID: db837fcdd213
Revises: e19f35f806e9
Create Date: 2021-02-26 23:53:06.456132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db837fcdd213'
down_revision = 'e19f35f806e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gender', table_name='people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('gender', 'people', ['gender'], unique=True)
    # ### end Alembic commands ###
