"""empty message

Revision ID: e19f35f806e9
Revises: 427bbe050a48
Create Date: 2021-02-26 16:55:37.612338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e19f35f806e9'
down_revision = '427bbe050a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('birth', sa.Date(), nullable=False))
    op.add_column('people', sa.Column('eye_color', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('gender', sa.String(length=250), nullable=False))
    op.add_column('people', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('people', sa.Column('skin', sa.String(length=250), nullable=False))
    op.drop_index('diameter', table_name='people')
    op.drop_index('orbital', table_name='people')
    op.drop_index('period', table_name='people')
    op.drop_index('population', table_name='people')
    op.create_unique_constraint(None, 'people', ['gender'])
    op.drop_column('people', 'population')
    op.drop_column('people', 'period')
    op.drop_column('people', 'diameter')
    op.drop_column('people', 'rotation_period')
    op.drop_column('people', 'orbital')
    op.drop_column('people', 'climate')
    op.add_column('planets', sa.Column('climate', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('orbital', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('period', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('population', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', sa.Integer(), nullable=False))
    op.drop_index('gender', table_name='planets')
    op.create_unique_constraint(None, 'planets', ['period'])
    op.create_unique_constraint(None, 'planets', ['orbital'])
    op.create_unique_constraint(None, 'planets', ['population'])
    op.create_unique_constraint(None, 'planets', ['diameter'])
    op.drop_column('planets', 'height')
    op.drop_column('planets', 'skin')
    op.drop_column('planets', 'eye_color')
    op.drop_column('planets', 'birth')
    op.drop_column('planets', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('gender', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planets', sa.Column('birth', sa.DATE(), nullable=False))
    op.add_column('planets', sa.Column('eye_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planets', sa.Column('skin', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planets', sa.Column('height', mysql.FLOAT(), nullable=False))
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_constraint(None, 'planets', type_='unique')
    op.create_index('gender', 'planets', ['gender'], unique=True)
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'period')
    op.drop_column('planets', 'orbital')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'climate')
    op.add_column('people', sa.Column('climate', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('people', sa.Column('orbital', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('people', sa.Column('rotation_period', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('people', sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('people', sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('people', sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'people', type_='unique')
    op.create_index('population', 'people', ['population'], unique=True)
    op.create_index('period', 'people', ['period'], unique=True)
    op.create_index('orbital', 'people', ['orbital'], unique=True)
    op.create_index('diameter', 'people', ['diameter'], unique=True)
    op.drop_column('people', 'skin')
    op.drop_column('people', 'height')
    op.drop_column('people', 'gender')
    op.drop_column('people', 'eye_color')
    op.drop_column('people', 'birth')
    # ### end Alembic commands ###
